export const loginService = () => {
  try {
  } catch (e) {
    `Failed while checking login credentials - ${(e as Error).message}`;
  }
};
